//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PassWord
    {
        public int CompanyCode { get; set; }
        public string EmployeeCode { get; set; }
        public string PassWord { get; set; }
        public string EmailAddress { get; set; }
        public string OldID { get; set; }
    }
}
